INSERT INTO CURRENCY_EXCHANGE (ID,CONVERSION_MULTIPLE,ENVIRONMENT,CURRENCY_FROM,CURRENCY_TO) VALUES(1001, 65, '', 'USD', 'INR');
INSERT INTO CURRENCY_EXCHANGE (ID,CONVERSION_MULTIPLE,ENVIRONMENT,CURRENCY_FROM,CURRENCY_TO) VALUES(1002, 25, '', 'AUD', 'INR');
INSERT INTO CURRENCY_EXCHANGE (ID,CONVERSION_MULTIPLE,ENVIRONMENT,CURRENCY_FROM,CURRENCY_TO) VALUES(1003, 75, '', 'EUR', 'INR');